[profile.default]
src = 'src'
out = 'out'
solc_version = '0.8.19'
optimizer_runs = 800000
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

[profile.ci]
fuzz_runs = 100000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
